<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.UH0bTY1' shared service.

return $this->privates['.service_locator.UH0bTY1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'depot' => ['privates', '.errored..service_locator.UH0bTY1.App\\Entity\\Depot', NULL, 'Cannot autowire service ".service_locator.UH0bTY1": it references class "App\\Entity\\Depot" but no such service exists.'],
    'depotRepository' => ['privates', 'App\\Repository\\DepotRepository', 'getDepotRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
], [
    'depot' => 'App\\Entity\\Depot',
    'depotRepository' => 'App\\Repository\\DepotRepository',
    'serializer' => '?',
]);
