<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.c_r3h3m' shared service.

return $this->privates['.service_locator.c_r3h3m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteController::addcompte' => ['privates', '.service_locator.K1GV3El', 'get_ServiceLocator_K1GV3ElService.php', true],
    'App\\Controller\\CompteController::listcompte' => ['privates', '.service_locator.O0uin.n', 'get_ServiceLocator_O0uin_NService.php', true],
    'App\\Controller\\DepotController::addDepot' => ['privates', '.service_locator.k0DCiXS', 'get_ServiceLocator_K0DCiXSService.php', true],
    'App\\Controller\\DepotController::listdepot' => ['privates', '.service_locator.UH0bTY1', 'get_ServiceLocator_UH0bTY1Service.php', true],
    'App\\Controller\\PartenaireController::addPartenaire' => ['privates', '.service_locator.5U4mfWm', 'get_ServiceLocator_5U4mfWmService.php', true],
    'App\\Controller\\PartenaireController::index' => ['privates', '.service_locator.mhlV_Pp', 'get_ServiceLocator_MhlVPpService.php', true],
    'App\\Controller\\PartenaireController::list' => ['privates', '.service_locator.omA4m1h', 'get_ServiceLocator_OmA4m1hService.php', true],
    'App\\Controller\\TransactionController::addTransaction' => ['privates', '.service_locator.ysofS8O', 'get_ServiceLocator_YsofS8OService.php', true],
    'App\\Controller\\TransactionController::index' => ['privates', '.service_locator.wckgq2u', 'get_ServiceLocator_Wckgq2uService.php', true],
    'App\\Controller\\UserController::addUser' => ['privates', '.service_locator.TUlHZkW', 'get_ServiceLocator_TUlHZkWService.php', true],
    'App\\Controller\\UserController::list' => ['privates', '.service_locator.yC11jyM', 'get_ServiceLocator_YC11jyMService.php', true],
    'App\\Controller\\UserController::token' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\CompteController:addcompte' => ['privates', '.service_locator.K1GV3El', 'get_ServiceLocator_K1GV3ElService.php', true],
    'App\\Controller\\CompteController:listcompte' => ['privates', '.service_locator.O0uin.n', 'get_ServiceLocator_O0uin_NService.php', true],
    'App\\Controller\\DepotController:addDepot' => ['privates', '.service_locator.k0DCiXS', 'get_ServiceLocator_K0DCiXSService.php', true],
    'App\\Controller\\DepotController:listdepot' => ['privates', '.service_locator.UH0bTY1', 'get_ServiceLocator_UH0bTY1Service.php', true],
    'App\\Controller\\PartenaireController:addPartenaire' => ['privates', '.service_locator.5U4mfWm', 'get_ServiceLocator_5U4mfWmService.php', true],
    'App\\Controller\\PartenaireController:index' => ['privates', '.service_locator.mhlV_Pp', 'get_ServiceLocator_MhlVPpService.php', true],
    'App\\Controller\\PartenaireController:list' => ['privates', '.service_locator.omA4m1h', 'get_ServiceLocator_OmA4m1hService.php', true],
    'App\\Controller\\TransactionController:addTransaction' => ['privates', '.service_locator.ysofS8O', 'get_ServiceLocator_YsofS8OService.php', true],
    'App\\Controller\\TransactionController:index' => ['privates', '.service_locator.wckgq2u', 'get_ServiceLocator_Wckgq2uService.php', true],
    'App\\Controller\\UserController:addUser' => ['privates', '.service_locator.TUlHZkW', 'get_ServiceLocator_TUlHZkWService.php', true],
    'App\\Controller\\UserController:list' => ['privates', '.service_locator.yC11jyM', 'get_ServiceLocator_YC11jyMService.php', true],
    'App\\Controller\\UserController:token' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
], [
    'App\\Controller\\CompteController::addcompte' => '?',
    'App\\Controller\\CompteController::listcompte' => '?',
    'App\\Controller\\DepotController::addDepot' => '?',
    'App\\Controller\\DepotController::listdepot' => '?',
    'App\\Controller\\PartenaireController::addPartenaire' => '?',
    'App\\Controller\\PartenaireController::index' => '?',
    'App\\Controller\\PartenaireController::list' => '?',
    'App\\Controller\\TransactionController::addTransaction' => '?',
    'App\\Controller\\TransactionController::index' => '?',
    'App\\Controller\\UserController::addUser' => '?',
    'App\\Controller\\UserController::list' => '?',
    'App\\Controller\\UserController::token' => '?',
    'App\\Controller\\CompteController:addcompte' => '?',
    'App\\Controller\\CompteController:listcompte' => '?',
    'App\\Controller\\DepotController:addDepot' => '?',
    'App\\Controller\\DepotController:listdepot' => '?',
    'App\\Controller\\PartenaireController:addPartenaire' => '?',
    'App\\Controller\\PartenaireController:index' => '?',
    'App\\Controller\\PartenaireController:list' => '?',
    'App\\Controller\\TransactionController:addTransaction' => '?',
    'App\\Controller\\TransactionController:index' => '?',
    'App\\Controller\\UserController:addUser' => '?',
    'App\\Controller\\UserController:list' => '?',
    'App\\Controller\\UserController:token' => '?',
]);
