<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ysofS8O' shared service.

return $this->privates['.service_locator.ysofS8O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'compte' => ['privates', 'App\\Repository\\CompteRepository', 'getCompteRepositoryService.php', true],
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'transaction' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService.php', true],
    'user' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'compte' => 'App\\Repository\\CompteRepository',
    'entityManager' => '?',
    'serializer' => '?',
    'transaction' => 'App\\Repository\\TransactionRepository',
    'user' => 'App\\Repository\\UserRepository',
    'validator' => '?',
]);
