<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTGQ3MDI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTGQ3MDI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTGQ3MDI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTGQ3MDI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTGQ3MDI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TGQ3MDI',
    'container.build_id' => 'dbd487d5',
    'container.build_time' => 1571787781,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTGQ3MDI');
